version: '3.8'

services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=shams
    ports:
      - '5291:5432'
  


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5290
    restart: always
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "5290:5290"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: event_management
      DB_USER: postgres
      DB_PASSWORD: shams
     
