# Generated by Django 4.1.6 on 2023-02-03 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_id', models.IntegerField()),
                ('sub_title', models.CharField(max_length=255)),
                ('other_info', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_1_rank', models.IntegerField()),
                ('event_2_rank', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('event_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='event.event')),
                ('event_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='event.event')),
            ],
        ),
    ]
