# Generated by Django 4.1.6 on 2023-02-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstat',
            name='event_link',
            field=models.CharField(default='1-2', max_length=50),
            preserve_default=False,
        ),
    ]
