# Generated by Django 4.1.6 on 2023-02-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventstat_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstat',
            name='ranker',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
