# Generated by Django 4.1.6 on 2023-02-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_change_fields_and_alter_raw_active_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_1_severity', models.IntegerField()),
                ('event_2_severity', models.IntegerField()),
                ('event_link', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('event_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='event.event')),
                ('event_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='event.event')),
            ],
        ),
    ]
