# Generated by Django 4.1.6 on 2023-02-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresult',
            name='event_1_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='event_2_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
