# Generated by Django 4.1.6 on 2023-02-16 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventresult_event_1_avg_eventresult_event_2_avg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventresult',
            old_name='event_1_severity',
            new_name='event_severity_score',
        ),
        migrations.RenameField(
            model_name='eventstat',
            old_name='event_1_rank',
            new_name='event_1_score',
        ),
        migrations.RenameField(
            model_name='eventstat',
            old_name='event_2_rank',
            new_name='event_2_score',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_link',
        ),
        migrations.RemoveField(
            model_name='eventresult',
            name='event_1',
        ),
        migrations.RemoveField(
            model_name='eventresult',
            name='event_1_avg',
        ),
        migrations.RemoveField(
            model_name='eventresult',
            name='event_2',
        ),
        migrations.RemoveField(
            model_name='eventresult',
            name='event_2_avg',
        ),
        migrations.RemoveField(
            model_name='eventresult',
            name='event_2_severity',
        ),
        migrations.RemoveField(
            model_name='eventresult',
            name='event_link',
        ),
        migrations.RemoveField(
            model_name='eventresult',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='eventstat',
            name='ranker',
        ),
        migrations.RemoveField(
            model_name='eventstat',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='eventresult',
            name='abstract',
            field=models.TextField(default=datetime.datetime(2023, 2, 16, 10, 14, 28, 989618)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventresult',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 10, 14, 38, 107687)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventresult',
            name='event_id',
            field=models.CharField(default=123, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventresult',
            name='location',
            field=models.CharField(default='Kabul, AF', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventresult',
            name='title',
            field=models.CharField(default='Title of event', max_length=255),
            preserve_default=False,
        ),
    ]
