# Generated by Django 4.1.7 on 2023-04-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
